config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # 默认路径
  root  "movies#index"

  get  "/faq"  =>  "pages#faq"

  # 管理员帐号下的电影管理
  namespace  :admin  do
    resources :movies  do
      resources  :buyers,  :controller  =>  "movie_buyers"
      resources  :reviews  # 评论

      member  do
        post  "reorder"
      end

      collection  do
        post  "bulk_update"
      end
    end
  end

  #  搜索及评论、收藏功能
  resources  :movies  do
    member  do
      post  :join  #  加入收藏
      post  :quit  #  取消收藏
    end

    collection  do
      get 'search'   # 搜索
    end

    resources  :reviews  # 评论
  end

  namespace  :account  do
    resources  :collections   # 电影收藏
  end




end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController
  before_action  :set_movie, only: [:show, :edit, :update, :destroy]
  before_action  :authenticate_user!, except: [:show, :index]


  def  reorder
    @movie  =  Movie.find(params[:id])
    @movie.row_order_position  =  params[:position]
    @movie.save!

    respond_to  do  |format|
      format.html  {  redirect_to  admin_movies_path}
      format.json  {  render  :json  =>  {  :message  =>  "ok" } }
    end

  end

  def  bulk_update
    total  =  0
    Array(params[:ids]).each  do  |movie_id|
      movie  =  Movie.find(movie_id)
      if   params[:commit]  ==  I18n.t(:bulk_update)
        movie.status  =  params[:movie_status]
        if  movie.save
          total  +=  1
        end
      elsif  params[:commit]  ==  I18n.t(:bulk_delete)
        movie.destroy
        total  +=  1
      end
    end

    flash[:alert]  =  "成功完成 #{total} 笔"
    redirect_to  admin_movies_path
  end


  def   index
    @movies  =  Movie.all.rank(:row_order)
  end

  def  new
    @movie  =  Movie.new
    @movie.tickets.build
    @movie.attachments.build
  end

  def  create
    @movie  =  Movie.new(movie_params)
    @movie.user  =  current_user

    if  @movie.save
      redirect_to  admin_movies_path
    else
      render  :new
    end

  end

  def  show
    @reviews  =   @movie.reviews.recent
    unless  @reviews.present?
      @avg_review  =  0
      @reviews.length  ==  0
    else
      @avg_review  =    @reviews.average(:rating).present? ? @reviews.average(:rating).round(2)  : 0
    end
  end

  def  edit
    @movie.tickets.build  if   @movie.tickets.empty?
    @movie.attachments.build  if   @movie.attachments.empty?
  end

  def  update
    if  @movie.update(movie_params)
      redirect_to  admin_movies_path
    else
      render  :edit
    end
  end

  def  destroy
    @movie.destroy
    redirect_to  admin_movies_path
  end

  private

  def  set_movie
    @movie  =  Movie.find_by_friendly_id!(params[:id])
  end

  def  movie_params
    params.require(:movie).permit(:title, :description, :movie_length, :director, :rating, :image, :is_hidden,
                                  :tickets_attributes  =>  [:id,  :name,  :description,  :price, :_destroy], :attachments_attributes  =>  [:id,  :attachment, :description, :_destroy] )
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action  :set_movie, only: [:show, :edit, :update, :destroy]
  before_action  :authenticate_user!, except: [:show, :index]


  def  search
    if  params[:search].present?
      @movies  =  Movie.search(params[:search]).find(params[:id])
    else
      @movies  =  Movie.all
    end
  end

   #  收藏电影
  def  join
    @movie  =  Movie.find(params[:id])
    if  !current_user.is_member_of?(@movie)
      current_user.join_collection!(@movie)
      flash[:notice]  =  "成功收藏电影, #{@movie.title}!"
    else
      flash[:warning]  =  "已经收藏了！"
    end

    redirect_to  movie_path(@movie)
  end

  #  取消收藏电影
  def  quit
    @movie  =  Movie.find(params[:id])
    if current_user.is_member_of?(@movie)
      current_user.quit_collection!(@movie)
      flash[:notice]  =  "已取消收藏!"
    else
      flash[:warning]  =  "未收藏!"
    end

    redirect_to  movie_path(@movie)
  end

  def   index
    @movies  =  Movie.where(:is_hidden => false).only_public.rank(:row_order)
  end

  def  new
    @movie  =  Movie.new
  end

  def  create
    @movie  =  Movie.new(movie_params)

    if  @movie.save
      redirect_to  @movie
    else
      render  :new
    end

  end

  def  show
    @reviews  =   @movie.reviews.recent
    unless  @reviews.present?
      @avg_review  =  0
      @reviews.length  ==  0
    else
      @avg_review  =  @reviews.average(:rating).present? ?  @reviews.average(:rating).round(2)  : 0
    end

    set_page_title  @movie.title
    # set_page_description  "#{@movie.description}"   一般情况下使用
    page_description  =  view_context.truncate(@movie.description, length: 100)  # description过长时使用
  end

  def  edit
  end

  def  update
    if  @movie.update(movie_params)
      redirect_to  @movie
    else
      render  :edit
    end
  end

  def  destroy
    @movie.destroy
    redirect_to  movies_path
  end



  private

  def  set_movie
    @movie  =  Movie.only_available.find_by_friendly_id!(params[:id])  # 如果活动是 draft 的话，经过 only_available scope 就会找不到，这就是我们的目的
  end

  def  movie_params
    params.require(:movie).permit(:title, :description, :movie_length, :director, :rating, :image, :is_hidden)
  end

end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def  render_movie_description(movie)
    simple_format(movie.description)
  end
end

app/views/admin/movies/_form.html.erb
<%  if  @movie.errors.any?  %>
  <ul>
    <%  @movie.errors.full_messages.each  do  |error|  %>
      <li><%=  error  %></li>
    <%  end  %>
  </ul>
<%  end  %>


  <div class="form-group">
    <%=  f.input :title, input_html: { class: "form-control" }, :autofocus  =>  true %>
  </div>

  <div class="form-group">
    <%=  f.input :description, input_html: { class: "form-control" }, as: :ckeditor  %>
  </div>

  <div class="form-group">
    <%=  f.input :movie_length, input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%=  f.input :director, input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%=  f.input :rating, input_html: { class: "form-control" }  %>
  </div>

  <div  class="form-group">
    <%=  f.input  :image, as: :file  %>
  </div>

  <div class="form-group">
    <%= f.input  :is_hidden  %>
  </div>

  <hr>
  <%=  f.nested_fields_for   :attachments  do  |ff|  %>
    <fieldset  style="border-left:  5px  solid  #bbb;  margin-bottom:  10px;  padding: 10px;">
      <legend>Attachment</legend>
      <div class="form-group">
        <%=  ff.label  :attachment   %>
        <%=  ff.file_field   :attachment,   class:  "form-control"   %>
        <%  if  ff.object.attachment.present?   %>
        已上传档案  <%=  link_to   ff.object.description,  ff.object.attachment.url,  :target  =>  "_blank"  %>

        <%  end  %>
      </div>

      <div class="form-group">
        <%=  ff.label   :description  %>
        <%=  ff.text_field  :description,  class: "form-control"  %>
      </div>

      <%=  ff.remove_nested_fields_link   "移除这个电影",    class: "btn  btn-danger"  %>
    </fieldset>
  <%  end  %>

   <p class="text-right">
     <%=  f.add_nested_fields_link   :attachments,  "新增电影",  class: "btn  btn-default"  %>
   </p>

  <hr>
  <%=  f.nested_fields_for  :tickets  do  |ff|  %>
    <fieldset  style=" border-left:  5px  solid  #bbb;  margin-bottom:  10px;  padding: 10px;">
      <legend>Ticket</legend>
      <div class="form-group">
        <%=  ff.label  :name  %>
        <%=  ff.text_field  :name,  :class  =>  "form-control", :required  =>  true  %>

        <div class="help-block  with-errors"></div>
      </div>

      <div class="form-group">
        <%=  ff.label  :description  %>
        <%=  ff.text_area  :description,  :class  =>  "form-control"  %>

        <div class="help-block  with-errors"></div>
      </div>

      <div class="form-group">
        <%=  ff.label  :price  %>
        <%=  ff.number_field  :price,  :class  =>  "form-control", :required  =>  true  %>

        <div class="help-block  with-errors"></div>
      </div>
    </fieldset>
    <%=  ff.remove_nested_fields_link  "移除这个票据",  :class  =>  "btn  btn-danger"  %>
  <%  end %>

  <p  class="text-right">
    <%=  f.add_nested_fields_link  :tickets, "新增票据",  :class  =>  "btn  btn-default"  %>
  </p>

 <hr>
 
  <script>
    $("form").validator();
  </script>

app/views/admin/movies/edit.html.erb
<h1>编辑电影</h1>
<%=  simple_form_for  [:admin, @movie]  do  |f|  %>
  <%=  render  :partial  =>  "form",  :locals  =>  { :f  =>  f} %>

  <div class="form-group">
    <%=  f.submit  "Submit",  class: "btn  btn-primary" %>
    <%=  link_to("Cancel", admin_movies_path) %>
  </div>

<%  end  %>

app/views/admin/movies/index.html.erb
<p  class="text-right">
  <%=  link_to("New  movie", new_admin_movie_path, class: "btn  btn-primary")  %>
</p>

  <%=  form_tag  bulk_update_admin_movies_path,  class: "form-inline"  do  %>
  <table  class="table">
    <thead>
      <tr>
          <th><%=  check_box_tag  "全选", "1", false, id: "toggle_all"  %></th>
          <th>Movie.Name</th>
          <th>Actions</th>
      </tr>
    </thead>
    <tbody   class="sortable">
      <%  @movies.each  do  |movie| %>
      <tr  data-reorder-url="<%=   reorder_admin_movie_path(movie)  %>">
          <td><%=  check_box_tag   "ids[]",  movie.id  %></td>
          <td>
            <span  class="sortable_icon">☰</span>
            <%=  link_to  movie.title, admin_movie_path(movie)  %>
          </td>
          <td>
            <%=  link_to  "置顶",  reorder_admin_movie_path(movie, :position  =>  :first),  :method  =>  :post,  :class  =>  "btn btn-default"  %>
            <%=  link_to  "置底",  reorder_admin_movie_path(movie,  :position  =>  :last),  :method  =>  :post,  :class  =>  "btn  btn-default"  %>
            <%=  link_to  "Buyers",  admin_movie_buyers_path(movie), class: "btn btn-default"  %>
            <%=  link_to  "Edit",  edit_admin_movie_path(movie),  class: "btn btn-primary" %>
            <%=  link_to  "Delete",  admin_movie_path(movie),  method: :delete, date: { confir: "Are  you  sure?" },  class: "btn  btn-danger" %>
          </td>
      <% end %>
      </tr>
    </tbody>

  </table>

    <p>
      <%=  select_tag  :movie_status, options_for_select( Movie::STATUS.map{  |s|  [t(s, :scope  =>  "movie.status"), s] }), class: "form-control"  %>
      <%=  submit_tag  t(:bulk_update),  class: "btn  btn-primary"  %>
      <%=  submit_tag  t(:bulk_delete),  class: "btn  btn-danger", data: { confirm: "Are  you  sure?" }  %>
    </p>
  <%  end %>

<script>
  $("#toggle_all").click(function(){
    if  (  $(this).prop("checked") ) {
      $("input[name='ids[]']").prop("checked", true)
    }
    else {
      $("input[name='ids[]']").prop("checked", false)
      }
  })

  $(".sortable").sortable({
    axis: 'y',      //  限制只能上下拖拉
    items: 'tr',    //  拖动整个tr
    cursor: 'move', //  变更拖拉时的 icon
    handle:  ".sortable_icon",  // 限制只有点 ☰ 才能开始拖拉，当去除这行代码时，整个tr都可以进行拖拉

    stop:  function(e, ui){    //  当拖拉结束时，会调用这个方法
      ui.item.children('td').effect('highlight', {}, 1000)
    },
    update: function(e, ui){    //当拖拉结束时并且 DOM 上的位置变更时，会调用这个方法
      reorder_ul  =  ui.item.data('reorder-url')
      position  =  ui.item.index()   //  取得顺序
      $ajax({
        type: 'POST',
        url: reorder_url,
        dataType: 'json',
        data: { position:  position}
      })
    }
  });
</script>

app/views/admin/movies/new.html.erb
<h1>新增电影</h1>
<%=  simple_form_for  [:admin, @movie]  do  |f|  %>
  <%=  render  :partial  =>  "form",  :locals  =>  { :f  =>  f} %>
  
  <div class="form-group">
    <%=  f.submit  "Submit",  class: "btn  btn-primary" %>
    <%=  link_to("Cancel", admin_movies_path) %>
  </div>

<%  end  %>

app/views/admin/movies/show.html.erb
<div  class="row">
  <div  class="col-md-4">
    <h3><%=  @movie.title  %></h3>
    <p>
      <%  if  @movie.image.present?  %>
        <%=  image_tag  @movie.image.url(:medium) %>
      <%  else  %>
        <%=  image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail")  %>
      <%  end  %>
    </p>
  </div>

  <div  class="col-md-6">
    <strong>片长：</strong>
    <%=  @movie.movie_length  %>
    <br>
    <strong>导演：</strong>
    <%=  @movie.director %>
    <br>
    <strong>电影评分：</strong>
    <%= @movie.rating  %>
    <div class="star-rating"  data-score= <%= @avg_review %> ></div>
    <em><%=  "#{@reviews.length}人评价" %></em>
  </div>

</div>

<br>
<div  class="col-md-9">
  <ul>
    <%  @movie.attachments.each  do  |a|  %>
      <li><%=  link_to  a.description,  a.attachment.url,  :target  =>  "_blank"  %></li>
    <%  end  %>
  </ul>
  剧情简介：
      <p><%= render_movie_description(@movie)  %></p>

      <!--－－ 新增评论 －－-->
      <hr>
      <%= simple_form_for  [@movie, @movie.reviews.build]  do  |f|  %>
        评价：<div id="star-rating"></div>
        <%=  f.input  :content,  class: "form-control"  %>
        <%=  f.button  :submit,  disable_with: "Submiting...", class: "btn  btn-primary"  %>
      <% end  %>

      <!--－－ 评论展示区 －－-->
      <hr>
      <%  if   @reviews.blank? %>
      <h3>还没有人评论，抢个沙发吧！</h3>
      <%=  link_to("Write a  review", new_movie_review_path(@movie), class: "btn btn-primary") %>
      <%  else  %>
        <%  @reviews.each  do |review|  %>
          <%=  review.user.email  %>
          <div class="star-rating"  data-score= <%= review.rating %> ></div>
          <%=  review.created_at.strftime("%Y/%m/%d, %I:%M  %P")  %><br>
          <%=  review.content  %>
          <hr>
        <%  end  %>
      <%  end  %>

  <%= link_to("back", admin_movies_path)  %>
  <%= link_to("Edit", edit_admin_movie_path(@movie) ) %>
  <%= link_to("Destroy", admin_movie_path(@movie), method: :delete, data: { confirm: "Are  you  sure?" } ) %>
</div>


<!---reviews index(list)---->
<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

<!---reviews  new(form) ---->
<script>
    $('#star-rating').raty({
      path: '/assets/',
      scoreName: 'review[rating]' });
</script>