config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # 默认路径
  root  "movies#index"

  get  "/faq"  =>  "pages#faq"

  # 管理员帐号下的电影管理
  namespace  :admin  do
    resources :movies  do
      resources  :buyers,  :controller  =>  "movie_buyers"
      resources  :reviews  # 评论

      member  do
        post  "reorder"
      end

      collection  do
        post  "bulk_update"
      end
    end
  end

  #  搜索及评论、收藏功能
  resources  :movies  do
    member  do
      post  :join  #  加入收藏
      post  :quit  #  取消收藏
    end

    collection  do
      get 'search'   # 搜索
    end

    resources  :reviews  # 评论
  end

  namespace  :account  do
    resources  :collections   # 电影收藏
  end




end

app/models/movie.rb
class Movie < ApplicationRecord

  #  建立 movie 和 attachment 之间的关系
  has_many  :attachments,  :class_name  =>  "MovieAttachment", :dependent  =>  :destroy
  accepts_nested_attributes_for  :attachments,  :allow_destroy  =>  true,  :reject_if  =>  :all_blank

  #  只有  public 状态下可以在前台显示
  scope  :only_public,  -> {  where( :status  =>  "public" ) }
  scope  :only_available,  ->  {  where( :status  =>  ["public", "private"] ) }

  #  建立  movie  和  buyer 之间的关系
  has_many  :buyers,  :dependent  =>  :destroy

  #  验证之前生成乱码
  before_validation   :generate_friendly_id,  :on  =>  :create

  #  调整电影的顺序
  include  RankedModel
  ranks  :row_order

  #  三种状态
  STATUS  =  ["hidden", "public", "draft"]
  validates_inclusion_of  :status, :in  =>  STATUS

  #  大数据级的搜索
  searchkick
  scope  :recent, ->  { order("created_at  DESC") }

  # 建立 movie 和 attachment 之间的关系
  has_many  :tickets, :dependent  =>  :destroy,  :inverse_of  =>  :movie
  accepts_nested_attributes_for  :tickets, :allow_destroy  =>  true,  :reject_if  =>  :all_blank

  # 收藏电影功能
  has_many  :collections  # 收藏电影
  has_many  :members, through: :collections, source: :user


  # 评论功能
  belongs_to  :user
  has_many  :reviews, dependent: :destroy   # 电影留言关系，dependent: :destroy表示联级删除


  #  验证title, description不得为空
  validates :title, presence: true

  #  paperclip  图片上传
  has_attached_file :image, styles: { medium: "400x600>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def   to_param
    self.friendly_id
  end

  #  生成随机乱码
  def  generate_friendly_id
    self.friendly_id  ||=   SecureRandom.uuid
  end

end

app/controllers/admin/movie_buyers_controller.rb
class Admin::MovieBuyersController < ApplicationController


  before_action  :find_movie

  def  index
    @q  =  @movie.buyers.ransack(params[:q])

    @buyers  =  @q.result.includes(:ticket).order("id  DESC").page(params[:page])

    if   params[:buyer_id].present?
      @buyers  =  @buyers.where(  :id  =>  params[:buyer_id].split(",") )
    end

    if   params[:start_on].present?
      @buyers  =  @buyers.where( "created_at  >=  ?",  Date.parse(params[:start_on]).beginning_of_day  )
    end

    if   params[:end_on].present?
      @buyers   =  @buyers.where( "created_at  <=  ?",  Date.parse(params[:end_on]).end_of_day )
    end

    if  Array(params[:statuses]).any?
      @buyers  =  @buyers.by_status(params[:statuses])
    end

    if  Array(params[:ticket_ids]).any?
      @buyers  =  @buyers.by_ticket(params[:ticket_ids])
    end

    if  params[:status].present?  &&  Buyer::STATUS.include?(params[:status])
      @buyers  =  @buyers.by_status(params[:status])
    end

    if  params[:ticket_id].present?
      @buyers  =  @buyers.by_ticket(params[:ticket_id])
    end

  end

  def  show
    @buyer  =  @movie.buyers.find_by_uuid(params[:id])
  end

  def  new
  end

  def  create
    @buyer  =  @movie.buyers.new(buyer_params)
    @buyer.ticket  =  @movie.tickets.find( params[:buyer][:ticket_id] )
    @buyer.status  =  "confirmed"
    @buyer.user  =  current_user

    if  @buyer.save
      redirect_to  admin_movie_buyers_path(@movie)
    else
      render  "new"
    end
  end

  def  edit
    @buyer  =  @movie.buyers.find_by_uuid(params[:id])
  end

  def  update
    @buyer  =  @movie.buyers.update(buyer_params)
    @buyer.ticket  =  @movie.tickets.find(params[:buyer][:ticket_id])
    @buyer.status  =  "confirmed"
    @buyer.user  =  current_user

    if  @buyer.save
      redirect_to   admin_movie_buyers_path(@movie)
    else
      render "edit"
    end
  end

  def  destroy
    @buyer  =  @movie.buyers.find_by_uuid(params[:id])
    @buyer.destroy

    redirect_to  admin_movie_buyers_path(@movie)
  end



  protected

  def  find_movie
    @movie  =  Movie.find_by_friendly_id(params[:movie_id])
  end

  def   buyer_params
    params.require(:buyer).permit(:name, :email, :cellphone,  :ticket, :status, :bio)
  end

end

app/helpers/admin/movie_buyers_helper.rb
module Admin::MovieBuyersHelper
  def   buyer_filters(options)
    params.permit(:status, :ticket_id).merge(options)
  end
end

app/views/admin/movie_buyers/index.html.erb
<h1><%= @movie.title %> / Buyers</h1>

<p class="text-right">
<%= link_to "New Buyer", new_admin_movie_buyer_path(@movie), :class => "btn btn-primary" %>
</p>

<%  if  false  %>
  <div class="submenu">
      <div class="btn-group">
        <%= link_to "全部 (#{@movie.buyers.size})", admin_movie_buyers_path(  buyer_filters(:status =>   nil)), :class => "btn btn-success btn-group #{(params[:status].blank?) ? "active" : ""}" %>
        <% Buyer::STATUS.each do |s| %>
          <%= link_to t(s, :scope => "buyer.status")  + " (#{@movie.buyers.by_status(s).size})",   admin_movie_buyers_path(buyer_filters(:status => s)), :class => "btn btn-success btn-group #{(  params[:status] == s) ? "active" : ""}" %>
          <% end %>
      </div>

      <div class="btn-group">
        <%= link_to "全部 (#{@movie.buyers.size})",  admin_movie_buyers_path(buyer_filters(:ticket_id =>   nil)), :class => "btn btn-default btn-group #{(params[:ticket_id].blank?) ? "active" : ""}" %>
        <% @movie.tickets.each do |t| %>
          <%= link_to t.name + " (#{@movie.buyers.by_ticket(t).size})", admin_movie_buyers_path(  buyer_filters(:ticket_id => t.id)), :class => "btn btn-default btn-group #{(params[:ticket_id].to_i == t.id)   ? "active" : ""}" %>
        <% end %>
      </div>
  </div>
<%  end  %>

<%=  search_form_for  @q,  :url  =>   admin_movie_buyers_path(@movie)   do   |f|   %>
  <p><%=  f.search_field  :name_cont,  :placeholder  =>  "姓名",  :class  =>  "form-control"  %></p>
  <p><%=  f.search_field  :email_cont,  :placeholder  =>  "E-mail", :class  =>  "form-control"  %></p>

  <p>
    <%=  text_field_tag  :buyer_id,  params[:buyer_id],  :placeholder  =>  "报名编号，可用,号区隔",  :class  =>  "form-control"  %>
  </p>

  <P>
    <%  Buyer::STATUS.each  do  |s|  %>
      <label>
        <%=  check_box_tag  "statuses[]", s, Array(params[:statuses]).include?(s)  %>
        <%=  t(s, :scope  =>  +  "buyer.status")  %>( <%=  @movie.buyers.by_status(s).size  %>)
      </label>
    <%  end  %>
  </P>
  <p>
    <%  @movie.tickets.each  do  |t|  %>
      <label>
        <%=  check_box_tag  "ticket_ids[]", t.id,  Array(params[:ticket_ids]).include?(t.id.to_s)  %>
        <%=  t.name  %>(<%=  + @movie.buyers.where( :ticket_id  =>  t.id ).size  %>)
      </label>
    <%  end  %>
  </p>
  <p>
    报名日期：<%=  date_field_tag   :start_on,  params[:start_on]  %>~<%=  date_field_tag  :end_on,  params[:end_on]   %>
  </p>

  <p  class="text-right">
    <%=  submit_tag  "送出筛选",  :class  =>  "btn  btn-primary"  %>
  </p>
<%  end  %>

<table class="table">
  <tr>
    <th>ID</th>
    <th>Ticket</th>
    <th>Name</th>
    <th>Status</th>
    <th>E-mail</th>
    <th>建立时间</th>
    <th>Actions</th>
  </tr>
  <% @buyers.each do |buyer| %>
    <tr>
      <td><%= buyer.id %></td>
      <td><%= buyer.ticket.name %></td>
      <td><%= buyer.name %></td>
      <td><%= t( buyer.status, :scope => "buyer.status") %></td>
      <td><%= buyer.email %></td>
      <td><%= buyer.created_at %></td>
      <td>
        <%= link_to "Edit", edit_admin_movie_buyer_path(@movie, buyer), :class => "btn btn-default" %>
        <%= link_to "Delete", admin_movie_buyer_path(@movie, buyer), :method => "delete", :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger" %>
    </tr>
  <% end %>
</table>

<p class="text-center">
  <%=  paginate  @buyers  %>
</p>