config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # 默认路径
  root  "movies#index"

  get  "/faq"  =>  "pages#faq"

  # 管理员帐号下的电影管理
  namespace  :admin  do
    resources :movies  do
      resources  :buyers,  :controller  =>  "movie_buyers"
      resources  :reviews  # 评论

      member  do
        post  "reorder"
      end

      collection  do
        post  "bulk_update"
      end
    end
  end

  #  搜索及评论、收藏功能
  resources  :movies  do
    member  do
      post  :join  #  加入收藏
      post  :quit  #  取消收藏
    end

    collection  do
      get 'search'   # 搜索
    end

    resources  :reviews  # 评论
  end

  namespace  :account  do
    resources  :collections   # 电影收藏
  end




end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <%  user_facing_flashes.each  do  |key, value| %>
    <div class="alert alert-dismissable alert-<%=  flash_class(key) %> ">
      <button class="close"  data-dismiss="alert">x</button>
      <%= value %>
    </div>
  <%  end  %>
<%  end  %>

app/views/common/_footer.html.erb
<footer class="container"  style="margin-top: 100px;">
  <p class="text-center">Copyright  ©2017   movies_review
    <br>Design  by   goflife
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="nav navbar-default"  role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a  class="navbar-brand"  href="/">Movies</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%  if  !current_user  %>
          <li><%=  link_to("注册", new_user_registration_path ) %></li>
          <li><%=  link_to("登陆", new_user_session_path ) %></li>
        <%  else  %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle"  data-toggle="dropdown">
              Hi!, <%=  current_user.email  %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <%  if  current_user.admin?  %>
                <li><%=  link_to("admin  movies", admin_movies_path) %></li>
              <%  end  %>

              <li><%=  link_to("我的收藏", account_collections_path) %></li>
              <li><%=  link_to("退出", destroy_user_session_path, method: :delete ) %></li>
            </ul>
          </li>
        <%   end   %>
      </ul>
      <%= form_tag   search_movies_path, method: :get, class: "navbar-form  navbar-right", role: "search"  do  %>
        <p>
          <%=  text_field_tag  :search, params[:search], class: "form-control" %>
          <%= submit_tag  "search", name: nil, class: "btn  btn-default" %>
        </p>
      <% end %>
    </div>
   </div>
</nav>